version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "mmartinortiz"
    labels:
      - "dependencies"
      - "automated"
    groups:
      actions:
        patterns:
          - "*"
